# Generated by Django 2.2.4 on 2020-07-13 18:29

from django.db import migrations
import phonenumbers

def normalize_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_dirty_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_dirty_phonenumber):
            flat.owner_phone_pure = phonenumbers.format_number(parsed_dirty_phonenumber, phonenumbers.PhoneNumberFormat.E164)
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200713_2128'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumbers),
    ]
