# Generated by Django 2.2.4 on 2020-07-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_phone_pure',
            new_name='phone_pure',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
    ]
