# Generated by Django 2.2.4 on 2020-07-13 19:47

from django.db import migrations

def copy_flat_owners_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(full_name=flat.owner,
                                    phonenumber=flat.owners_phonenumber,
                                    defaults={'phone_pure': flat.owner_phone_pure})

def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200713_2246'),
    ]

    operations = [
        migrations.RunPython(copy_flat_owners_to_owners, move_backward),
    ]
